In [3]:
import numpy as np
import pandas as pd

In [47]:
batsman = pd.read_csv('batsman_runs_ipl.csv')
batsman

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [45]:
# set_index(dataframe) -> inplace
batsman.set_index('batter',inplace=True)
batsman

                batsman_run
batter
A Ashish Reddy          280
A Badoni                161
A Chandila                4
A Chopra                 53
A Choudhary              25
...                     ...
Yash Dayal                0
Yashpal Singh            47
Younis Khan               3
Yuvraj Singh           2754
Z Khan                  117

[605 rows x 1 columns]

In [44]:
# reset_index(series + dataframe) -> drop parameter
batsman.reset_index(inplace=True)
batsman

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [48]:
# how to replace existing index without loosing
batsman.reset_index().set_index('batting_rank')

KeyError: "None of ['batting_rank'] are in the columns"

In [50]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks)
marks_series

maths       67
english     57
science     89
hindi      100
dtype: int64

In [51]:
# Convert series to dataframe using reset_index
marks_series.reset_index()

     index    0
0    maths   67
1  english   57
2  science   89
3    hindi  100